apiVersion: apps/v1
kind: Deployment
metadata:
  name: warmup-sandbox
  namespace: default
  labels:
    app: warmup-sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: warmup-sandbox
  template:
    metadata:
      labels:
        app: warmup-sandbox
    spec:
      containers:
        - name: warmup-sandbox
          image: bcky/warmup-sandbox:latest
          ports:
            - containerPort: 8080