apiVersion: apps/v1
kind: Deployment
metadata:
  name: warmup-sandbox
  namespace: default
  labels:
    app: warmup-sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: warmup-sandbox
  template:
    metadata:
      labels:
        app: warmup-sandbox
    spec:
      containers:
        - name: warmup-sandbox
          image: bcky/warmup-sandbox:latest
          args:
            - --spring.profiles.active=prod
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
