apiVersion: v1
kind: Service
metadata:
  name: warmup-sandbox
spec:
  selector:
    app: warmup-sandbox
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080